const themes = require('./themes.js');

module.exports = {
  components: {
    categories: [
      {
        name: 'INPUTS',
        include: [
          'src/components/Autocomplete/Autocomplete.tsx',
          'src/components/Button/Button.tsx',
          'src/components/ButtonBase/ButtonBase.tsx',
          'src/components/ButtonGroup/ButtonGroup.tsx',
          'src/components/Checkbox/Checkbox.tsx',
          'src/components/FloatingActionButton/FloatingActionButton.tsx',
          'src/components/IconButton/IconButton.tsx',
          'src/components/Radio/Radio.tsx',
          'src/components/RadioGroup/RadioGroup.tsx',
          'src/components/Rating/Rating.tsx',
          'src/components/Select/Select.tsx',
          'src/components/Slider/Slider.tsx',
          'src/components/SplitButton/SplitButton.tsx',
          'src/components/Switch/Switch.tsx',
          'src/components/TextField/TextField.tsx',
          'src/components/ToggleButton/ToggleButton.tsx',
          'src/components/ToggleButtonGroup/ToggleButtonGroup.tsx',
        ],
      },
      {
        name: 'DATA DISPLAY',
        include: [
          'src/components/Avatar/Avatar.tsx',
          'src/components/AvatarGroup/AvatarGroup.tsx',
          'src/components/Badge/Badge.tsx',
          'src/components/Chip/Chip.tsx',
          'src/components/Divider/Divider.tsx',
          'src/components/Icon/Icon.tsx',
          'src/components/SvgIcon/SvgIcon.tsx',
          'src/components/MaterialIcon/MaterialIcon.tsx',
          'src/components/List/List.tsx',
          'src/components/Table/Table.tsx',
          'src/components/Tooltip/Tooltip.tsx',
          'src/components/Typography/Typography.tsx',
        ],
      },
      {
        name: 'FEEDBACK',
        include: [
          'src/components/Alert/Alert.tsx',
          'src/components/Backdrop/Backdrop.tsx',
          'src/components/CircularProgress/CircularProgress.tsx',
          'src/components/Dialog/Dialog.tsx',
          'src/components/LinearProgress/LinearProgress.tsx',
          'src/components/Skeleton/Skeleton.tsx',
          'src/components/Snackbar/Snackbar.tsx',
        ],
      },
      {
        name: 'SURFACES',
        include: [
          'src/components/Accordion/Accordion.tsx',
          'src/components/AppBar/AppBar.tsx',
          'src/components/Card/Card.tsx',
          'src/components/Masonry/Masonry.tsx',
          'src/components/Paper/Paper.tsx',
          'src/components/SpeedDial/SpeedDial.tsx',
          'src/components/SpeedDialAction/SpeedDialAction.tsx',
        ],
      },
      {
        name: 'NAVIGATION',
        include: [
          'src/components/BottomNavigation/BottomNavigation.tsx',
          'src/components/Breadcrumbs/Breadcrumbs.tsx',
          'src/components/Drawer/Drawer.tsx',
          'src/components/Link/Link.tsx',
          'src/components/Menu/Menu.tsx',
          'src/components/Pagination/Pagination.tsx',
          'src/components/Stepper/Stepper.tsx',
          'src/components/Tabs/Tabs.tsx',
        ],
      },
      {
        name: 'LAYOUT',
        include: [
          'src/components/Box/Box.tsx',
          'src/components/Container/Container.tsx',
          'src/components/Grid/Grid.tsx',
          'src/components/ImageList/ImageList.tsx',
          'src/components/Stack/Stack.tsx',
        ],
      },
      {
        name: 'TRANSITIONS',
        include: [
          'src/components/Collapse/Collapse.tsx',
          'src/components/Fade/Fade.tsx',
          'src/components/Grow/Grow.tsx',
          'src/components/Slide/Slide.tsx',
          'src/components/Zoom/Zoom.tsx',
        ],
      },
      {
        name: 'MUI-X CHARTS',
        include: [
          'src/components/BarChart/BarChart.tsx',
          'src/components/LineChart/LineChart.tsx',
          'src/components/PieChart/PieChart.tsx',
          'src/components/ScatterChart/ScatterChart.tsx',
          'src/components/SparkLineChart/SparkLineChart.tsx',
          'src/components/Gauge/Gauge.tsx',
          'src/components/RadarChart/RadarChart.tsx',
        ],
      },
      {
        name: 'MUI-X',
        include: [
          'src/components/DataGrid/DataGrid.tsx',
          'src/components/DatePicker/DatePicker.tsx',
          'src/components/TimePicker/TimePicker.tsx',
          'src/components/DateTimePicker/DateTimePicker.tsx',
          'src/components/SimpleTreeView/SimpleTreeView.tsx',
          'src/components/TreeItem/TreeItem.tsx',
        ],
      },
      {
        name: 'CHILDREN COMPONENTS',
        include: [
          'src/components/AccordionActions/AccordionActions.tsx',
          'src/components/AccordionDetails/AccordionDetails.tsx',
          'src/components/AccordionSummary/AccordionSummary.tsx',
          'src/components/AlertTitle/AlertTitle.tsx',
          'src/components/BottomNavigationAction/BottomNavigationAction.tsx',
          'src/components/CardActionArea/CardActionArea.tsx',
          'src/components/CardActions/CardActions.tsx',
          'src/components/CardContent/CardContent.tsx',
          'src/components/CardHeader/CardHeader.tsx',
          'src/components/CardMedia/CardMedia.tsx',
          'src/components/DialogActions/DialogActions.tsx',
          'src/components/DialogContent/DialogContent.tsx',
          'src/components/DialogContentText/DialogContentText.tsx',
          'src/components/DialogTitle/DialogTitle.tsx',
          'src/components/FormControl/FormControl.tsx',
          'src/components/FormControlLabel/FormControlLabel.tsx',
          'src/components/FormGroup/FormGroup.tsx',
          'src/components/FormHelperText/FormHelperText.tsx',
          'src/components/FormLabel/FormLabel.tsx',
          'src/components/ImageListItem/ImageListItem.tsx',
          'src/components/ImageListItemBar/ImageListItemBar.tsx',
          'src/components/InputAdornment/InputAdornment.tsx',
          'src/components/InputLabel/InputLabel.tsx',
          'src/components/ListItem/ListItem.tsx',
          'src/components/ListItemAvatar/ListItemAvatar.tsx',
          'src/components/ListItemButton/ListItemButton.tsx',
          'src/components/ListItemIcon/ListItemIcon.tsx',
          'src/components/ListItemSecondaryAction/ListItemSecondaryAction.tsx',
          'src/components/ListItemText/ListItemText.tsx',
          'src/components/ListSubheader/ListSubheader.tsx',
          'src/components/MenuItem/MenuItem.tsx',
          'src/components/MenuList/MenuList.tsx',
          'src/components/Step/Step.tsx',
          'src/components/StepContent/StepContent.tsx',
          'src/components/StepLabel/StepLabel.tsx',
          'src/components/Tab/Tab.tsx',
          'src/components/TableBody/TableBody.tsx',
          'src/components/TableCell/TableCell.tsx',
          'src/components/TableContainer/TableContainer.tsx',
          'src/components/TableFooter/TableFooter.tsx',
          'src/components/TableHead/TableHead.tsx',
          'src/components/TablePagination/TablePagination.tsx',
          'src/components/TableRow/TableRow.tsx',
          'src/components/Toolbar/Toolbar.tsx',
        ],
      },
    ],
    wrapper: 'src/wrapper/UXPinWrapper.tsx',
    webpackConfig: 'webpack.config.js',
  },
  name: 'MUI9-UXPin-Merge',
  settings: {
    componentType: 'mui',
    themes: themes,
    useUXPinProps: true,
    useConvertingToUXPinClassic: true,
    useIcons: { iconMap: 'https://uc.uxpin.com/mui-icons.json', component: 'MaterialIcon' },
  },
};
